import Head from 'next/head';
// import Image from 'next/image';

import ArticleList from '../components/article/ArticleList';
import Tags from '../components/home/Tags';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home-page">
        <div className="article-list">
          <ArticleList />
        </div>
        <div className="sidebar">
          <p>Popular Tags</p>

          <Tags />
        </div>
      </div>
    </div>
  );
}
